services:
  web:
    build: .
    container_name: dcrm_crm
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-django-insecure-wrd@k5c63l-25ln)85jwma^uf$he_n077de(m!-(rhiu5#*d+q}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-False}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0}
      - DJANGO_DB_PATH=/app/data/db.sqlite3
    volumes:
      - dcrm_data:/app/data
    restart: unless-stopped

volumes:
  dcrm_data:
