# Generated by Django 6.0.6 on 2026-06-26 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_rol', models.CharField(choices=[('cliente', 'Cliente'), ('vendedor', 'Vendedor'), ('gestor', 'Gestor'), ('admin', 'Administrador')], db_column='rol', default='cliente', max_length=20)),
                ('_telefono', models.CharField(blank=True, db_column='telefono', max_length=15, null=True)),
                ('_direccion', models.CharField(blank=True, db_column='direccion', max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
